language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

git:
  depth: false

cache:
  directories:
    - /home/travis/.cargo
    - /home/travis/.rustup

before_cache:
  - rm -rf /home/travis/.cargo/registry

before_script:
  - rustup component add clippy
  - cargo install critcmp --force
  # - cargo install semverver --force

script:
  - cargo check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test

after_success:
  - .config/benchmark.sh
