language: rust
rust:
  - stable
  - beta
  - nightly

matrix:
  allow_failures:
    - rust: nightly
  fast_finish: true

git:
  depth: false

cache:
  directories:
    - /home/travis/.cargo
    - /home/travis/.rustup

before_cache:
  - rm -rf /home/travis/.cargo/registry

before_script:
  - command -v cargo-clippy 2>&1 || rustup component add clippy
  - command -v critcmp 2>&1 || cargo install critcmp
  # - cargo install semverver --force

script:
  - cargo check
  - cargo test
  - cargo bench --bench lookup_benches -- --save-baseline $TRAVIS_COMMIT
  - cargo clippy --all-targets --all-features -- -D warnings
