language: rust
rust:
  - stable
  - beta
  - nightly

cache:
  directories:
    - /home/travis/.cargo
    - /home/travis/.rustup

before_cache:
  - rm -rf /home/travis/.cargo/registry

before_script:
  - rustup component add clippy
  - cargo install critcmp --force
  # - cargo install semverver --force

script:
  - cargo check
  - cargo clippy --all-targets --all-features -- -D warnings
  - cargo test
  - git checkout master
  - cargo bench --bench lookup_benches -- --noplot --save-baseline before
  - git checkout $TRAVIS_COMMIT
  - cargo bench --bench lookup_benches -- --noplot --save-baseline after
  - critcmp before after
